# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-08 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_link', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_publishing.PublishVideo'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
