# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-14 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_publishing', '0004_auto_20170408_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishvideo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
