# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-08 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videopublishing', '0002_auto_20170408_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
