# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videopublishing', '0003_auto_20170408_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishvideo',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
