# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-14 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videopublishing', '0005_publishvideo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishvideo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
