# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-14 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videopublishing', '0007_auto_20170414_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_Create',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Video_Create',
        ),
    ]
