# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import videopublishing.models


class Migration(migrations.Migration):

    dependencies = [
        ('videopublishing', '0010_auto_20170424_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_create',
            name='image_of_course',
            field=models.CharField(max_length=100, null=True, validators=[videopublishing.models.validate_image_url]),
        ),
        migrations.AlterField(
            model_name='course_create',
            name='year_of_study',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
